// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: transfer_instruction.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ExternalId           string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	PartnerRefNo         string                 `protobuf:"bytes,2,opt,name=partner_ref_no,json=partnerRefNo,proto3" json:"partner_ref_no,omitempty"`
	CustomerNumber       string                 `protobuf:"bytes,3,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	AccountType          string                 `protobuf:"bytes,4,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	BeneficiaryAccountNo string                 `protobuf:"bytes,5,opt,name=beneficiary_account_no,json=beneficiaryAccountNo,proto3" json:"beneficiary_account_no,omitempty"`
	BeneficiaryBankCode  string                 `protobuf:"bytes,6,opt,name=beneficiary_bank_code,json=beneficiaryBankCode,proto3" json:"beneficiary_bank_code,omitempty"`
	Amount               string                 `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionDate      string                 `protobuf:"bytes,8,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	CustomerReference    string                 `protobuf:"bytes,9,opt,name=customer_reference,json=customerReference,proto3" json:"customer_reference,omitempty"`
	Channel              string                 `protobuf:"bytes,10,opt,name=channel,proto3" json:"channel,omitempty"`
	Remarks              string                 `protobuf:"bytes,11,opt,name=remarks,proto3" json:"remarks,omitempty"`
	Email                string                 `protobuf:"bytes,12,opt,name=email,proto3" json:"email,omitempty"`
	Address              string                 `protobuf:"bytes,13,opt,name=address,proto3" json:"address,omitempty"`
	Citizenship          string                 `protobuf:"bytes,14,opt,name=citizenship,proto3" json:"citizenship,omitempty"`
	TransferPurpose      string                 `protobuf:"bytes,15,opt,name=transfer_purpose,json=transferPurpose,proto3" json:"transfer_purpose,omitempty"`
	TransferActivity     string                 `protobuf:"bytes,16,opt,name=transfer_activity,json=transferActivity,proto3" json:"transfer_activity,omitempty"`
	CustomerType         string                 `protobuf:"bytes,17,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_transfer_instruction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_instruction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_instruction_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *TransferRequest) GetPartnerRefNo() string {
	if x != nil {
		return x.PartnerRefNo
	}
	return ""
}

func (x *TransferRequest) GetCustomerNumber() string {
	if x != nil {
		return x.CustomerNumber
	}
	return ""
}

func (x *TransferRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *TransferRequest) GetBeneficiaryAccountNo() string {
	if x != nil {
		return x.BeneficiaryAccountNo
	}
	return ""
}

func (x *TransferRequest) GetBeneficiaryBankCode() string {
	if x != nil {
		return x.BeneficiaryBankCode
	}
	return ""
}

func (x *TransferRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransferRequest) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *TransferRequest) GetCustomerReference() string {
	if x != nil {
		return x.CustomerReference
	}
	return ""
}

func (x *TransferRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *TransferRequest) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *TransferRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TransferRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TransferRequest) GetCitizenship() string {
	if x != nil {
		return x.Citizenship
	}
	return ""
}

func (x *TransferRequest) GetTransferPurpose() string {
	if x != nil {
		return x.TransferPurpose
	}
	return ""
}

func (x *TransferRequest) GetTransferActivity() string {
	if x != nil {
		return x.TransferActivity
	}
	return ""
}

func (x *TransferRequest) GetCustomerType() string {
	if x != nil {
		return x.CustomerType
	}
	return ""
}

var File_transfer_instruction_proto protoreflect.FileDescriptor

const file_transfer_instruction_proto_rawDesc = "" +
	"\n" +
	"\x1atransfer_instruction.proto\x12\bprotobuf\"\x83\x05\n" +
	"\x0fTransferRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12$\n" +
	"\x0epartner_ref_no\x18\x02 \x01(\tR\fpartnerRefNo\x12'\n" +
	"\x0fcustomer_number\x18\x03 \x01(\tR\x0ecustomerNumber\x12!\n" +
	"\faccount_type\x18\x04 \x01(\tR\vaccountType\x124\n" +
	"\x16beneficiary_account_no\x18\x05 \x01(\tR\x14beneficiaryAccountNo\x122\n" +
	"\x15beneficiary_bank_code\x18\x06 \x01(\tR\x13beneficiaryBankCode\x12\x16\n" +
	"\x06amount\x18\a \x01(\tR\x06amount\x12)\n" +
	"\x10transaction_date\x18\b \x01(\tR\x0ftransactionDate\x12-\n" +
	"\x12customer_reference\x18\t \x01(\tR\x11customerReference\x12\x18\n" +
	"\achannel\x18\n" +
	" \x01(\tR\achannel\x12\x18\n" +
	"\aremarks\x18\v \x01(\tR\aremarks\x12\x14\n" +
	"\x05email\x18\f \x01(\tR\x05email\x12\x18\n" +
	"\aaddress\x18\r \x01(\tR\aaddress\x12 \n" +
	"\vcitizenship\x18\x0e \x01(\tR\vcitizenship\x12)\n" +
	"\x10transfer_purpose\x18\x0f \x01(\tR\x0ftransferPurpose\x12+\n" +
	"\x11transfer_activity\x18\x10 \x01(\tR\x10transferActivity\x12#\n" +
	"\rcustomer_type\x18\x11 \x01(\tR\fcustomerTypeB\x15Z\x13./internal/protobufb\x06proto3"

var (
	file_transfer_instruction_proto_rawDescOnce sync.Once
	file_transfer_instruction_proto_rawDescData []byte
)

func file_transfer_instruction_proto_rawDescGZIP() []byte {
	file_transfer_instruction_proto_rawDescOnce.Do(func() {
		file_transfer_instruction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfer_instruction_proto_rawDesc), len(file_transfer_instruction_proto_rawDesc)))
	})
	return file_transfer_instruction_proto_rawDescData
}

var file_transfer_instruction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transfer_instruction_proto_goTypes = []any{
	(*TransferRequest)(nil), // 0: protobuf.TransferRequest
}
var file_transfer_instruction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transfer_instruction_proto_init() }
func file_transfer_instruction_proto_init() {
	if File_transfer_instruction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfer_instruction_proto_rawDesc), len(file_transfer_instruction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transfer_instruction_proto_goTypes,
		DependencyIndexes: file_transfer_instruction_proto_depIdxs,
		MessageInfos:      file_transfer_instruction_proto_msgTypes,
	}.Build()
	File_transfer_instruction_proto = out.File
	file_transfer_instruction_proto_goTypes = nil
	file_transfer_instruction_proto_depIdxs = nil
}
